DELIMITER $$

CREATE PROCEDURE num1(
    IN EMP_NUM VARCHAR(10),
    IN EMP_TITTLE VARCHAR(10),
    IN EMP_LNAME VARCHAR(50),
    IN EMP_FNAME VARCHAR(50),
    IN EMP_DOB DATE,
    IN EMP_HIRE_DATE DATE,
    IN EMP_ARE_CODE VARCHAR(10),
    IN EMP_PHONE VARCHAR(15),
    IN PARK_COD VARCHAR(10)
)
BEGIN
    INSERT INTO EMPLOYEE(EMP_NUM, EMP_TITTLE, EMP_LNAME, EMP_FNAME, EMP_DOB, EMP_HIRE_DATE, EMP_ARE_CODE, EMP_PHONE, PARK_COD)
    VALUES (EMP_NUM, EMP_TITTLE, EMP_LNAME, EMP_FNAME, EMP_DOB, EMP_HIRE_DATE, EMP_ARE_CODE, EMP_PHONE, PARK_COD);
END $$

DELIMITER ;
